
#pragma once

#define FAT32_DATA_MASK_PRESERVE		0xF0000000
#define FAT32_DATA_MASK_DATA			0x0FFFFFFF
#define FAT32_BAD_CLUSTER				0x0FFFFFF7
#define FAT32_FREE_CLUSTER				0x00000000
#define FAT32_END_OF_CLUSTER_CHAIN		0x0FFFFFFF
#define FAT32_END_OF_CLUSTER_CHAIN_THRESHOLD	0x0FFFFFF8
#define FAT32_IS_END_OF_CLUSTER_CHAIN(val)	((((val) & FAT32_DATA_MASK_DATA) >= FAT32_END_OF_CLUSTER_CHAIN_THRESHOLD) ? TRUE : FALSE)

typedef struct FAT32_FOBJ_DESC_INTERNAL
{
	DWORD	dwStartCluster;
	DWORD	dwCurrentCluster;
	QWORD	qwSize;
	QWORD	qwPointer;
	QWORD	qwAttributes;
	QWORD	qwNameLen;
	WCHAR	wName[1];

}FAT32_FOBJ_DESC_INTERNAL;

#define HANDLE_ALLOCATION_UNIT_FAT32	50

#define FAT32_VOL_ATTR_FAT_MODE_MASK	0x1
#define FAT32_VOL_ATTR_FAT_MODE_MIRRORING	0x0
#define FAT32_VOL_ATTR_FAT_MODE_ACTIVE	0x1
